# Generated by Django 5.2.16 on 2026-09-08 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0178_watchstate_watchstatechange_watchstatesequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.BigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("upsert", "Upsert"), ("delete", "Delete")],
                        default="upsert",
                        max_length=8,
                    ),
                ),
                ("position_seconds", models.PositiveIntegerField(default=0)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "origin_key",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_changes",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress change",
                "verbose_name_plural": "Progress changes",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(
                        fields=["user", "sequence"],
                        name="app_progres_user_id_03f694_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="app_progres_created_a24cd5_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "sequence"),
                        name="unique_progress_change_sequence",
                    )
                ],
            },
        ),
    ]
