# Generated by Django 5.2.16 on 2026-09-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0036_merge_20260905_1122"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpodderaccount",
            name="last_full_resync_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time a full (non-incremental) GPodder history resync ran",
                null=True,
            ),
        ),
    ]
