# Generated by Django 5.2.16 on 2026-09-07 20:29

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _constraint_exists(schema_editor, table_name, constraint_name):
    """Return True when the named index or constraint already exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        try:
            constraints = connection.introspection.get_constraints(
                cursor,
                table_name,
            )
        except Exception:  # noqa: BLE001 - introspection quirks shouldn't break migrate
            return False
    return constraint_name in constraints


class AddIndexIfNotExists(migrations.AddIndex):
    """Add an index only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(
            schema_editor,
            to_model._meta.db_table,  # noqa: SLF001
            self.index.name,
        ):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    """Add a constraint only when it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if _constraint_exists(
            schema_editor,
            to_model._meta.db_table,  # noqa: SLF001
            self.constraint.name,
        ):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0178_watchstate_watchstatechange_watchstatesequence"),
        ("integrations", "0036_merge_20260905_1122"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_kind",
                    models.CharField(
                        choices=[
                            ("plex", "Plex"),
                            ("jellyfin", "Jellyfin"),
                            ("emby", "Emby"),
                            ("kodi", "Kodi"),
                            ("stremio", "Stremio"),
                            ("audiobookshelf", "Audiobookshelf"),
                            ("generic", "Generic client"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "instance_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "profile_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("origin_key", models.CharField(max_length=128, unique=True)),
                ("approved_capabilities", models.JSONField(default=list)),
                ("approved_directions", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending approval"),
                            ("active", "Active"),
                            ("needs_reapproval", "Needs reapproval"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("kill_switch", models.BooleanField(default=False)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_bindings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync binding",
                "verbose_name_plural": "Sync bindings",
                "ordering": ["user", "client_kind", "instance_key"],
            },
        ),
        migrations.CreateModel(
            name="StateConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("divergent_watched", "Both sides changed watched state"),
                            ("digest_mismatch", "States diverged"),
                            (
                                "unattributable_unwatch",
                                "Nothing identifiable to retract",
                            ),
                            ("ambiguous_match", "More than one item matched"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "local_snapshot",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "remote_snapshot",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "base_snapshot",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_conflicts",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="integrations.syncbinding",
                    ),
                ),
            ],
            options={
                "verbose_name": "State conflict",
                "verbose_name_plural": "State conflicts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderStateObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("watched", models.BooleanField(default=False)),
                ("play_count", models.PositiveIntegerField(default=0)),
                ("watched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "local_revision_at_observation",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "local_digest_at_observation",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("source", models.CharField(blank=True, default="", max_length=32)),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_state_observations",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_state_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="integrations.syncbinding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider state observation",
                "verbose_name_plural": "Provider state observations",
            },
        ),
        migrations.CreateModel(
            name="SyncCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource", models.CharField(max_length=64)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Provider to Floppy"),
                            ("outbound", "Floppy to provider"),
                        ],
                        max_length=16,
                    ),
                ),
                ("cursor", models.CharField(blank=True, default="", max_length=512)),
                ("last_sequence", models.BigIntegerField(default=0)),
                (
                    "provider_cursor",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="integrations.syncbinding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync checkpoint",
                "verbose_name_plural": "Sync checkpoints",
            },
        ),
        migrations.CreateModel(
            name="UnresolvedExternalReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=32)),
                ("value", models.CharField(max_length=255)),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("unknown_id", "No matching item"),
                            ("unsupported_namespace", "Identifier type unsupported"),
                            ("ambiguous", "More than one item matched"),
                            ("unsupported_media_type", "Media type unsupported"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unresolved_references",
                        to="integrations.syncbinding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unresolved external reference",
                "verbose_name_plural": "Unresolved external references",
                "ordering": ["-last_seen_at"],
            },
        ),
        AddIndexIfNotExists(
            model_name="syncbinding",
            index=models.Index(
                fields=["user", "status"], name="integration_user_id_81fcdf_idx"
            ),
        ),
        AddConstraintIfNotExists(
            model_name="syncbinding",
            constraint=models.UniqueConstraint(
                fields=("user", "client_kind", "instance_key", "profile_key"),
                name="unique_sync_binding_identity",
            ),
        ),
        AddIndexIfNotExists(
            model_name="stateconflict",
            index=models.Index(
                fields=["user", "status"], name="integration_user_id_78311e_idx"
            ),
        ),
        AddConstraintIfNotExists(
            model_name="stateconflict",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("user", "item", "binding", "reason"),
                name="unique_open_state_conflict",
            ),
        ),
        AddIndexIfNotExists(
            model_name="providerstateobservation",
            index=models.Index(
                fields=["binding", "observed_at"], name="integration_binding_2c36f4_idx"
            ),
        ),
        AddConstraintIfNotExists(
            model_name="providerstateobservation",
            constraint=models.UniqueConstraint(
                fields=("binding", "item"), name="unique_provider_observation_per_item"
            ),
        ),
        AddConstraintIfNotExists(
            model_name="synccheckpoint",
            constraint=models.UniqueConstraint(
                fields=("binding", "resource", "direction"),
                name="unique_sync_checkpoint_position",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="unresolvedexternalreference",
            constraint=models.UniqueConstraint(
                fields=("binding", "namespace", "value", "reason_code"),
                name="unique_unresolved_external_reference",
            ),
        ),
    ]
