# Generated by Django 5.2.16 on 2026-09-08 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0178_watchstate_watchstatechange_watchstatesequence"),
        ("integrations", "0038_backfill_jellyfin_binding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundStateDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_revision", models.PositiveIntegerField(default=0)),
                (
                    "target_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "intent",
                    models.BooleanField(
                        default=True,
                        help_text="True to mark played remotely, False to mark unplayed.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_flight", "In flight"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True, default="")),
                (
                    "client_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "readback_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("echo_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.syncbinding",
                    ),
                ),
                (
                    "change",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="app.watchstatechange",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_deliveries",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound state delivery",
                "verbose_name_plural": "Outbound state deliveries",
                "ordering": ["binding", "item", "target_revision"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="integration_status_882653_idx",
                    ),
                    models.Index(
                        fields=["binding", "status"],
                        name="integration_binding_d5ea89_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("binding", "item", "target_revision"),
                        name="unique_delivery_per_revision",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "in_flight")),
                        fields=("binding", "item"),
                        name="unique_inflight_delivery_per_item",
                    ),
                ],
            },
        ),
    ]
