# Generated by Django 5.2.16 on 2026-09-08 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0039_outboundstatedelivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name="audiobookshelfaccount",
            name="abs_user_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Audiobookshelf user id, used to scope a sync binding.",
                max_length=255,
            ),
        ),
        AddFieldIfNotExists(
            model_name="jellyfinaccount",
            name="server_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jellyfin server GUID. Scopes a sync binding to one server, so pointing the same account at a different server stops rather than silently writing to it.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="EmbyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(help_text="Emby server URL")),
                ("api_key", models.TextField(help_text="Encrypted Emby API key")),
                (
                    "emby_user_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "emby_username",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("server_id", models.CharField(blank=True, default="", max_length=255)),
                ("connection_broken", models.BooleanField(default=False)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emby_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Emby account",
                "verbose_name_plural": "Emby accounts",
            },
        ),
        migrations.CreateModel(
            name="KodiAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(help_text="Kodi JSON-RPC endpoint URL")),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                (
                    "password",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted Kodi JSON-RPC password",
                    ),
                ),
                (
                    "instance_uuid",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("connection_broken", models.BooleanField(default=False)),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kodi_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kodi account",
                "verbose_name_plural": "Kodi accounts",
            },
        ),
    ]
