# Generated by Django 5.2.16 on 2026-09-08 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class CreateModelIfNotExists(migrations.CreateModel):
    """Create the table only when it is not already there."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Skip the CREATE TABLE on a database that already has it."""
        to_model = to_state.apps.get_model(app_label, self.name)
        table = to_model._meta.db_table  # noqa: SLF001
        with schema_editor.connection.cursor() as cursor:
            existing = schema_editor.connection.introspection.table_names(cursor)
        if table in existing:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0041_integrationeventreceipt_binding_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name="CatalogGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("catalog_ids", models.JSONField(default=list)),
                ("allow_playback_start", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog grant",
                "verbose_name_plural": "Catalog grants",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="integration_user_id_29946d_idx",
                    )
                ],
            },
        ),
    ]
