# Generated by Django 5.2.16 on 2026-09-08 23:09

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class CreateModelIfNotExists(migrations.CreateModel):
    """Create the table only when it is not already there."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Skip the CREATE TABLE on a database that already has it."""
        to_model = to_state.apps.get_model(app_label, self.name)
        table = to_model._meta.db_table  # noqa: SLF001
        with schema_editor.connection.cursor() as cursor:
            existing = schema_editor.connection.introspection.table_names(cursor)
        if table in existing:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0042_cataloggrant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name="RemoteAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manifest_url", models.URLField(max_length=2048)),
                ("addon_id", models.CharField(blank=True, default="", max_length=255)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("version", models.CharField(blank=True, default="", max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "manifest",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_addons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote add-on",
                "verbose_name_plural": "Remote add-ons",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "manifest_url"),
                        name="unique_remote_addon_per_user",
                    )
                ],
            },
        ),
    ]
