# Generated by Django 5.2.16 on 2026-09-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0037_gpodderaccount_last_full_resync_at"),
        ("integrations", "0044_integrationtoken_writable_list_ids"),
    ]

    operations = []
