# Generated by Django 5.2.16 on 2026-09-10 00:48

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0045_external_references"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externalreference",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RenameIndex(
            model_name="externalreference",
            new_name="integration_user_id_558d7e_idx",
            old_name="integrations_ex_user_id_8f34b1_idx",
        ),
        migrations.RenameIndex(
            model_name="externalreference",
            new_name="integration_user_id_70a21a_idx",
            old_name="integrations_ex_user_id_6dbf91_idx",
        ),
        migrations.RenameIndex(
            model_name="externalreference",
            new_name="integration_matched_8ca43c_idx",
            old_name="integrations_ex_matched_7e4b3a_idx",
        ),
        migrations.RenameIndex(
            model_name="plexwatchlistsyncitem",
            new_name="integration_user_id_e5fb7f_idx",
            old_name="integrations__user_id_1f8c46_idx",
        ),
        migrations.AlterField(
            model_name="externalreference",
            name="decision_note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="externalreference",
            name="media_type",
            field=models.CharField(
                choices=[("tv", "TV Show"), ("movie", "Movie"), ("episode", "Episode")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="externalreference",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="externalreference",
            name="source_account",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="plexwatchlistsyncitem",
            name="source_server_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
