# Generated by Django 5.2.16 on 2026-09-10 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0045_merge_20260909_1104"),
        ("integrations", "0046_alter_externalreference_options_and_more"),
    ]

    operations = []
