# Generated by Django 5.2.16 on 2026-08-25 08:18

from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    """Return True when a database column already exists."""
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.columns "
                "WHERE table_schema = current_schema() "
                "AND table_name = %s AND column_name = %s",
                [table_name, column_name],
            )
            return cursor.fetchone() is not None
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
        columns = {getattr(column, "name", column[0]) for column in description}
        return column_name in columns


class AddFieldIfNotExists(migrations.AddField):
    """Add a field only when the backing column doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        field = to_model._meta.get_field(self.name)
        if _column_exists(schema_editor, to_model._meta.db_table, field.column):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0131_alter_user_ui_language"),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name="user",
            name="custom_logo_data",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Normalized custom navigation logo",
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="custom_theme",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Validated custom application color palette",
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="detail_page_layouts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Visible and ordered sections for each detail page family",
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="logo_text",
            field=models.CharField(
                default="Floppy",
                help_text="Short navigation wordmark",
                max_length=32,
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="logo_text_font",
            field=models.CharField(
                choices=[
                    ("display", "Floppy display"),
                    ("sans", "Clean sans"),
                    ("serif", "Editorial serif"),
                    ("mono", "Technical mono"),
                ],
                default="display",
                help_text="Font family used by the navigation wordmark",
                max_length=12,
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="logo_text_size",
            field=models.PositiveSmallIntegerField(
                choices=[(size, f"{size}px") for size in range(16, 41)],
                default=23,
                help_text="Font size used by the navigation wordmark",
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="logo_text_spacing",
            field=models.SmallIntegerField(
                choices=[(spacing, f"{spacing}px") for spacing in range(-2, 7)],
                default=-1,
                help_text="Letter spacing used by the navigation wordmark",
            ),
        ),
        AddFieldIfNotExists(
            model_name="user",
            name="logo_text_weight",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (400, "Regular"),
                    (500, "Medium"),
                    (600, "Semibold"),
                    (700, "Bold"),
                    (800, "Extra bold"),
                    (900, "Black"),
                ],
                default=800,
                help_text="Font weight used by the navigation wordmark",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="logo_style",
            field=models.CharField(
                choices=[
                    ("colorful", "Original color"),
                    ("monochrome", "Monochrome"),
                    ("text", "Text"),
                    ("custom", "Custom image"),
                    ("hidden", "Hidden"),
                ],
                default="colorful",
                help_text="Preferred Floppy logo style",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("system", "System default"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("catppuccin_mocha", "Catppuccin Mocha"),
                    ("dracula", "Dracula"),
                    ("nord", "Nord"),
                    ("gruvbox", "Gruvbox"),
                    ("oled", "OLED"),
                    ("glass", "Glass cinema"),
                    ("plex", "Plex inspired"),
                    ("projector", "Projector"),
                    ("video_store", "Video store"),
                    ("custom", "Custom palette"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
